site_name: 智课方舟
site_url: https://bamboo-bookkeeping.doc.x-lf.cn/
repo_url: https://github.com/class-scheduling-system/develop-document
repo_name: bamboo-services/develop-document
copyright: Copyright &copy; 2022-2025 锋叶技术团队 All Righjs Reserved. 版权所有
theme:
  logo: /assets/images/favicon.png
  favicon: /assets/images/favicon.png
  name: material
  language: zh
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: 切换亮色模式
    - media: "(prefers-color-scheme: light)"
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换暗色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 依照系统进行模式切换
  features:
    - search
    - search.suggest
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.footer
    - navigation.sections
    - toc.follow
    - navigation.top
nav:
  - 欢迎: index.md
  - 开发信息: information.md
  - 赛题信息: competition.md
  - 设计:
    - 数据库设计: design/database_design.md
  - 开发:
    - 数据库准备: develop/database_prepare.md
    - 项目准备: develop/project_prepare.md
plugins:
  - search
extra_javascript:
  - assets/js/extra.js